Add docker buildx builder
palantir/distgo pull request #307
Opened 2023-01-06 16:51 UTC by andybradshaw

## Before this PR

## After this PR

==COMMIT_MSG==
Add support for multi-architecture builds with a docker `buildx` builder 
==COMMIT_MSG==

## Possible downsides?

2023-01-18 16:29 UTC, andybradshaw commented
Not entirely sure we should still be splitting this across the various repos/plugin assets, but it basically mirrors the existing dockerbuilder, just with a different underlying command structure, so figured it was okay to add here.

2023-01-24 21:12 UTC, nmiyake requested changes
Thanks for the PR! I'm supportive of adding the functionality, but per the feedback, would suggest that we add the functionality by adding a configuration point/value on the default Docker builder rather than creating an entirely new builder.

I would also like there to be unit and integration tests added to where they already exist for Docker builders to verify that the functionality works in the desired manner.

2023-01-24 21:12 UTC, nmiyake commented on dockerbuilder/buildxdockerbuilder/dockerbuilder.go
> +	var driverOptArgs []string
nit, but since `driverOptArgs` are appended to `args`, I think it's more readable to have this block after the declaration of the `args` variable

2023-01-24 21:12 UTC, nmiyake commented on dockerbuilder/buildxdockerbuilder/dockerbuilder.go
> +		return err
Helpful to include `string(out)` as part of the error for debugging

2023-01-24 21:12 UTC, nmiyake commented on dockerbuilder/buildxdockerbuilder/dockerbuilder.go
> +// Copyright 2016 Palantir Technologies, Inc.
nit, but since this is a new file, should be 2023 (I believe the license plugin on the repo would properly add the current year, but assume this is from a copy-paste of the default builder)

2023-01-24 21:12 UTC, nmiyake commented on dockerbuilder/buildxdockerbuilder/dockerbuilder.go
> +	dockerBuilderOutputInfo := productTaskOutputInfo.Product.DockerOutputInfos.DockerBuilderOutputInfos[dockerID]
It looks like most of this logic is shared with the default Docker builder.

Zooming out, it looks like the main differences between the `buildx` builder and the default builder are:
* Presence of `DriverOpts` in configuration
* Validating presence of Docker container driver
* Running `buildx build` instead of `build` as the base command

Given all of this, I think it may make more sense to implement the `buildx` functionality as a new optional behavior on the default builder rather than as an entirely new builder. That way, we wouldn't need to duplicate the core logic or the scaffolding for things like configuration, integration tests, etc.

We could either have a boolean flag or a default-empty optional configuration block and have either of those things signal that `buildx` should be used, in which case the `buildx` argument would be added to the `args` slice and the logic that ensures the driver would be run.

2023-01-24 21:17 UTC, nmiyake commented on changelog/@unreleased/pr-307.v2.yml
> +  description: Add support for multi-architecture builds with a docker `buildx` builder
The content here will likely change if the PR feedback is followed, but ultimately this will serve as the release note/documentation, so when the final approach is determined it would be nice to expand this to describe more of what changed and how it can be used.

2023-01-24 22:47 UTC, nmiyake commented
I've updated the RFC with this feedback, but from a big picture perspective I think this PR should be changed to:

1. Define the concept/contract for where the output for where the `docker buildx` manifest directory and output should go
2. Make it so the `buildx` build operation writes its output in a standardized manner to the location decided above (rather than delegating that to the managed builder)
3. Either have `buildx` as its own separate builder (as this PR does) OR modify the default builder so that it supports writing OCI output and have a mode flag that controls whether the builder builds just daemon images, just OCI image output, or daemon image + OCI output
  * If it's the former, implementation should still be refactored so that default and dockerx builder mostly share the underlying implementation rather than duplicating the code

2023-01-30 17:11 UTC, andybradshaw commented
> Would suggest that we add the functionality by adding a configuration point/value on the default Docker builder rather than creating an entirely new builder.

Seems like there's not a good way right now to add any "options" to the builder, so we probably need to add a different constructor which gives us that flexibility. Added something with `Options` in the latest commit, but happy to take a different approach. Seems like everything we provide to the builder is optional at the moment, although this might not be the case with the Buildx output options.

> Define the concept/contract for where the output for where the `docker buildx` manifest directory and output should go

This makes sense, and will make it more obvious/consistent between `build` and `push` tasks. I've done this by adding a `ProductDockerDistOutputDir` which takes a DockerID and produces a path in the dist dir. I first attempted to handle this by adding something to the `DockerBuilderOutputInfo` struct, but that seemed to not fit very well. Let me know if you had other ideas about how to handle this.

> Make it so the `buildx` build operation writes its output in a standardized manner to the location decided above (rather than delegating that to the managed builder)

I have some concerns around how this can interact with the existing implementation around "buildArgs"... right now, the builder has very few opinions about what it's doing, but adding this behavior here means not all provided args will be respected (or rather, it's up to how docker parses them). I think it's more correct to have this behavior here, but think it means we might need to scope down what consumers can provide.

2023-01-30 21:40 UTC, andybradshaw commented
Another annoying thing we're probably going to need to handle here is the fact that the `oci` artifact isn't quite what we want. In the resulting tarball we produce, the `index.json` is an image index which contains all the tags that we applied during the build:

```json
{
  "schemaVersion": 2,
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.index.v1+json",
      "digest": "sha256:be0dd4591f7ceba283693862ee1d1cdc51cda4c32631bfd520ebba3a4810767b",
      "size": 705,
      "annotations": {
        "io.containerd.image.name": "palantir/test:0.0.1",
        "org.opencontainers.image.created": "2023-01-05T16:49:10Z",
        "org.opencontainers.image.ref.name": "0.0.1"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.index.v1+json",
      "digest": "sha256:be0dd4591f7ceba283693862ee1d1cdc51cda4c32631bfd520ebba3a4810767b",
      "size": 705,
      "annotations": {
        "io.containerd.image.name": "palantirtest:snapshot",
        "org.opencontainers.image.created": "2023-01-05T16:49:10Z",
        "org.opencontainers.image.ref.name": "snapshot"
      }
    }
  ]
}
```

I don't think this is actually what we want as I've run into issues trying to push this manifest to a registry, since it sort of breaks how these things are meant to be used (What is the named reference to the above image index? Do both `0.0.1` and `snapshot` point to it? If so, why duplicate this information?). I think we need to follow the first digest and use that image index as the top-level image-index instead (which points to the various architectures in the index), which we'll push for each of the tags:

```json
{
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "schemaVersion": 2,
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "digest": "sha256:ae76b86cdfca59a11fc30d0986ef46742da678d379c9d291ccc1eb8401a4c420",
         "size": 1115,
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "digest": "sha256:9e7c6cea504c77e1d56ec9fa33a0bf6bb79cd2372c20c866eed2ba6c1f672430",
         "size": 1115,
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

It's a little annoying that we have to do this at all, but with the "output" responsibilities shifting from the managed plugin to this repo, I think we'll need to move that here 🙁

2023-01-30 21:53 UTC, nmiyake commented
I don't fully understand the last comment... I'm not as familiar with the index files, but from the examples you posted above, in the first one it looks like the index file itself points to different index files (referenced by tag name?), while the second one references the specific manifests of the images.

It might help to make the expected outputs for each case more explicit.

## "build" step

### For regular/current Docker builder:
* Result of "docker build" is that image is built and pushed/published in local Docker daemon using all of the associated tags

### Proposal for Docker buildx builder:
* Result of "docker buildx" is:
  * A TGZ file that contains the "full" Docker buildx output: a top-level image index file and all of the individual images that are referenced from that file laid out in the proper format (where just distributing/publishing the TGZ is sufficient)
  * Tags are *not* part of this output -- they are only used/referenced on push

## "push" step

### For regular/current Docker builder:
* "Push" operation issues a "push" command to local Docker daemon using tags for the build and the provided publish URL
* This depends on "build" having already been run and tagging the images in the Docker daemon with the expected tags/names

### Proposal for Docker buildx builder:
* "Push" operation pushes the TGZ (index file + individual images) to the publish URL for each of the tags
* Depends on the TGZ output already being created/existing in expected location, and the push to remote is the first/only thing that actually applies the tags

Is the above correct and what we want? If it's off, can you identify what's off about it/clarify what the proposal actually is?

2023-01-31 17:59 UTC, andybradshaw commented
>  A TGZ file that contains the "full" Docker buildx output: a top-level image index file and all of the individual images that are referenced from that file laid out in the proper format (where just distributing/publishing the TGZ is sufficient)
> 
>  Tags are _not_ part of this output -- they are only used/referenced on push

Yes, I believe this is the output we want, which means we need to modify the tarball produced by the build to get rid to the level of indirection that the `buildx` process is currently introducing.

> the push to remote is the first/only thing that actually applies the tags

Yeah, that seems right. Tagging during the build isn't really needed, since the artifact will be the same and we know the full set of tags we want to push during that task.

2023-02-02 22:41 UTC, andybradshaw commented
@nmiyake think this is probably ready for another pass if we're in agreement about the oci-layout as the "dist" that we want here

2023-02-07 21:26 UTC, nmiyake requested changes
Thanks, I think this approach is an improvement. Given that this task isn't technically a `dist` task, having the "dist" output be the directory that uses an OCI layout is likely fine. There's a part of me that wonders whether it would be better to produce a TGZ of the OCI layout so we still have a single-file dist output, but there may not really be a practical reason to do this if the only consumer is the `publish` task and that task wants/needs an on-disk directory structure anyway.

2023-02-07 21:26 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +		return err
Likely helpful to include `string(out)` as a wrapped message for debugging

2023-02-07 22:08 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +	if d.Output&OCITarball != 0 {
As discussed in sync, add check here and error if `d.Output == 0` and/or if none of the relevant bits are set (we expect that every `build` operation should build at least 1 valid output).

2023-02-09 00:13 UTC, nmiyake requested changes

2023-02-09 00:13 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +		return errors.New("Output type of docker builder must be specified")
We should keep this, but I don't think it catches all cases -- if someone provides `1 << 3` right now, I believe that it won't be 0, but also won't match either of the existing masks.

We should probably have a `buildRan := false` boolean, flip it to true for any mask match, and then throw an error at the end of all flag checks if it is still `false`

2023-02-09 00:13 UTC, nmiyake commented on changelog/@unreleased/pr-307.v2.yml
> +  description: Add support for multi-architecture builds with a docker `buildx` builder
Changelog should be updated. It should reflect that the new functionality has been added, but should also mention that it is only exposed at an API level and that this change alone does not make it possible for end users of `distgo` to create multi-architecture Docker images.

2023-02-10 19:08 UTC, andybradshaw commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +		return errors.New("Output type of docker builder must be specified")
Added a const for all the build types and checked against that

2023-02-13 23:48 UTC, nmiyake requested changes
Thanks! Some minor requests for modification.

Also, can you add at least one test that invokes this behavior in `dockerbuilder/defaultdockerbuilder/integration_test/integration_test.go`?

2023-02-13 23:48 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +	if err := os.Rename(path.Join(destOCILayoutDir, "blobs", idxManifest.Manifests[0].Digest.Algorithm, idxManifest.Manifests[0].Digest.Hex), path.Join(destOCILayoutDir, "index.json")); err != nil {
I believe this should be `filepath.Join` since it's for dealing with renames/moves on the local disk.

2023-02-13 23:48 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +// ensureDockerContainerDriver ensures there is a buildx builder that uses the docker-container driver, currently
Reword to make a bit more natural/readable:

> ensureDockerContainerDriver ensures there is a buildx builder that uses the docker-container driver, which is required for building multi-arch images.  If a buildx builder does not exist, creates one and sets it as the default. This is required until docker finishes supporting multi-arch containers in the daemon.

Also, it would be helpful if there was a linked issue for this (if one exists) and an explanation of what would be changed once this support does exist -- as it stands right now, I'm not sure what the criteria is for this being removed/changed when the support is eventually added/complete.

2023-02-13 23:48 UTC, nmiyake commented on distgo/product.go
> +func (p *ProductTaskOutputInfo) ProductDockerOCIDistOutputDir(dockerID DockerID) string {
Please add documentation -- I think something like the following would work:

```
// ProductDockerOCIDistOutputDir returns the output directory for the Docker OCI dist outputs, which is
// "{{ProjectDir}}/{{OutputDir}}/{{ProductID}}/oci-{{DockerID}}". If the builder for a given DockerID uses the buildx builder for multi-architecture images, the output is written to this directory.
//
// Note that this scheme uses the namespace for dist outputs, so if a product has a DockerID "X" and a dist with
// DistID "oci-X", then the output directories will be the same and the behavior will be undefined -- this is a
// known issue/risk that we are accepting as part of the design.
```

2023-02-13 23:48 UTC, nmiyake commented on distgo/product.go
> +func (p *ProductTaskOutputInfo) ProductDockerOCIDistOutputDir(dockerID DockerID) string {
Minor, but I would move this function next to `ProductDistOutputDir`

2023-02-13 23:48 UTC, nmiyake commented on distgo/product.go
> +	return ProductDistOutputDir(p.Project, p.Product, DistID(fmt.Sprintf("oci-%s", dockerID)))
I think the path here should mirror the other outputs by including the `{{Version}}` as part of the path after `Product` -- that way if the Docker builder is run on multiple versions of the product the output is kept separate.

Also, my example comment above about conflicting with `dist` may not completely be true given how we construct this output path.

2023-02-13 23:48 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +	createContextArgs := []string{"context", "create", string(dockerID)}
Can you add comment here with link to the docs you included in the Slack chat to document that we're intentionally doing this as a 2 step process because of the known issue?

2023-02-14 00:18 UTC, gcampbell12 commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +	if err := archiver.DefaultTar.Unarchive(destOCILayoutDir, sourceOCITarball); err != nil {
Looks like this is the wrong way round, should be source tarball and the directory to extract it into
```suggestion
	if err := archiver.DefaultTar.Unarchive(sourceOCITarball, destOCILayoutDir); err != nil {
```

2023-02-14 00:18 UTC, gcampbell12 commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +		destDir := productTaskOutputInfo.ProductDockerOCIDistOutputDir(dockerID)
This directory needs to exist prior to passing it to the build command, could we run it through `os.MkdirAll`?

2023-02-14 18:27 UTC, nmiyake commented
Never mind regarding integration test -- integration tests run based on rendered config, and since there's no way to instantiate this builder via config in this PR, it's not possible to test via integration tests.

2023-02-14 19:03 UTC, andybradshaw commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +		destDir := productTaskOutputInfo.ProductDockerOCIDistOutputDir(dockerID)
Added.

2023-02-14 19:03 UTC, andybradshaw commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +	if err := archiver.DefaultTar.Unarchive(destOCILayoutDir, sourceOCITarball); err != nil {
Good catch! Updated

2023-02-14 19:03 UTC, andybradshaw commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +	createContextArgs := []string{"context", "create", string(dockerID)}
Added a comment and linked to the circle article.

2023-02-14 19:03 UTC, andybradshaw commented on distgo/product.go
> +	return ProductDistOutputDir(p.Project, p.Product, DistID(fmt.Sprintf("oci-%s", dockerID)))
Yep, since this uses `ProductDistOutputDir`, it should pull out the version internally:
```
path.Join(projectInfo.ProjectDir, productOutputInfo.DistOutputInfos.DistOutputDir, string(productOutputInfo.ID), projectInfo.Version, string(distID))
```

2023-02-14 19:03 UTC, andybradshaw commented on distgo/product.go
> +func (p *ProductTaskOutputInfo) ProductDockerOCIDistOutputDir(dockerID DockerID) string {
Updated and moved.

2023-02-14 19:03 UTC, andybradshaw commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +// ensureDockerContainerDriver ensures there is a buildx builder that uses the docker-container driver, currently
Updated the comment and linked to the docs where it mentions that the docker daemon driver does not support it. I was unable to find a high-level [tracking issue here](https://github.com/docker/roadmap), might be worth creating one as it's pretty unclear the direction the project is taking.

2023-02-14 19:03 UTC, andybradshaw commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +	if err := os.Rename(path.Join(destOCILayoutDir, "blobs", idxManifest.Manifests[0].Digest.Algorithm, idxManifest.Manifests[0].Digest.Hex), path.Join(destOCILayoutDir, "index.json")); err != nil {
👍 good flag, updated the other locations where we did this as well (context dir and dockerfile path)

2023-02-14 19:29 UTC, nmiyake requested changes
Thanks! A few minor things to touch up, but should be ready after that.

2023-02-14 19:29 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +		return errors.New("A valid output type of docker builder must be specified")
Errors should not start with a capital letter -- that's generally a Go convention because errors are often chained in output.

2023-02-14 19:29 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +			return err
Wrap with an `errors.Wrapf` call so that stack trace is included

2023-02-14 19:29 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +		destFile := fmt.Sprintf("%s/image.tar", destDir)
This should be a `filepath.Join(destDir, "image.tar")`

2023-02-14 19:29 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +		return err
Wrap error

2023-02-14 19:29 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +		return err
Wrap error

2023-02-14 19:29 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +		return err
Wrap error

2023-02-14 19:29 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +		return errors.New("Top-level OCI image index does not contain any manifests. While this is a valid image index, it is unexpected and likely means something erroneous happened earlier in the build")
Use lowercase first letter and try to maintain as single segment:

```
top-level OCI image index does not contain any manifests -- while this is a valid image index, it is unexpected and likely means something erroneous happened earlier in the build
```

2023-02-14 19:29 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +		return err
Wrap error

2023-02-14 19:29 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +// ensureDockerContainerDriver ensures there is a buildx builder that uses the docker-container driver, which is
Looks like this comment is now repeated -- delete the section before this one.

2023-02-14 19:29 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +		return fmt.Errorf("failed to check for existence of buildx drivers: %s", string(out))
Use `errors.Wrapf` to include stack trace and also to include output of the original error (in addition to the string output)

2023-02-14 19:29 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +		return err
Just noting that these calls are fine as-is (don't need to be wrapped) since they call into other `distgo` functions, and the expectation is that in-library errors will already be the proper type (or wrapped if the underlying cause is due to external libraries)

2023-02-14 19:59 UTC, nmiyake approved these changes

2023-02-14 19:59 UTC, nmiyake commented on dockerbuilder/defaultdockerbuilder/dockerbuilder.go
> +		return err
Still needs to be wrapped, but low-pri/will not block.

2023-02-14 20:36 UTC, merged