Publish OCI artifacts
palantir/distgo pull request #339
Opened 2023-03-06 16:18 UTC by andybradshaw

## Before this PR

## After this PR

==COMMIT_MSG==
Add support for publishing OCI artifacts if they exist, and handles both image index and image manifest types.
==COMMIT_MSG==

## Possible downsides?

2023-03-08 17:31 UTC, nmiyake requested changes

2023-03-08 17:31 UTC, nmiyake commented on changelog/@unreleased/pr-339.v2.yml
> +fix:
nit, but this would probably be a "feature" or "improvement" (if this functionality already existed and you were fixing the failure that would be more of a fix, but we rolled back that behavior entirely)

2023-03-08 17:31 UTC, nmiyake commented on distgo/docker/docker_push.go
> +			switch idxManifest.Manifests[0].MediaType {
Is `idxManifest.Manifests` guaranteed to be exactly size 1? This will crash if `Manifests` is empty, and if there are more than 1 then they aren't considered?

2023-03-08 17:31 UTC, nmiyake commented on distgo/docker/docker_push.go
> +			switch idxManifest.Manifests[0].MediaType {
Also the nested `switch` statements make the cases a bit hard to follow (at first glance can be hard to tell whether a case is associated with inner or outer switch) -- can we decomp a bit? Would also help readability since this function is pretty large/dense

2023-03-08 17:31 UTC, nmiyake commented on distgo/docker/docker_push.go
> +		case types.OCIImageIndex:
Don't see a `default` case -- is an unknown media type fine to be a no-op, or is it a case that should never happen? If it's the latter, should add default handling that throws an error.

2023-03-08 17:31 UTC, nmiyake commented on distgo/docker/docker_push.go
> +			case types.OCIImageIndex:
Same question as previous switch statement: if `MediaType` doesn't match any case, is that an acceptable case where a noop is the correct result, or should there be a `default` case that throws on unrecognized media type?

2023-03-08 18:52 UTC, andybradshaw commented on distgo/docker/docker_push.go
> +		case types.OCIImageIndex:
Added `defaults`, should definitely be errors

2023-03-08 18:52 UTC, andybradshaw commented on distgo/docker/docker_push.go
> +			case types.OCIImageIndex:
Added

2023-03-08 18:52 UTC, andybradshaw commented on distgo/docker/docker_push.go
> +			switch idxManifest.Manifests[0].MediaType {
Added a `manifestMetadata` type, which should do some validation of index manifest (e.g. has non-zero manifests, all inner manifest media types match) and extracts the "has platform information" check.

It's still a bit dense, might be worth pulling the `remote.Write` and `remote.WriteIndex` into an interface so we can mock it/test this?

2023-03-08 18:52 UTC, andybradshaw commented on changelog/@unreleased/pr-339.v2.yml
> +fix:
Updated

2023-03-08 21:49 UTC, nmiyake requested changes

2023-03-08 21:49 UTC, nmiyake commented on distgo/docker/docker_push.go
> +		if len(idxManifest.Manifests) != 1 {
Line 141 also accesses `idxManifest.Manifests[0]`.

If we always expect to exist, would move this check up to line 137 and then have `manifest := idxManifest.Manifests[0]` and use that variable in the rest of this function

2023-03-08 21:49 UTC, nmiyake commented on distgo/docker/docker_push.go
> +		if len(idxManifest.Manifests) != 1 {
Ah wait it looks like this check is already done in `manifestMetadataFromIndexManifest`, so it's not required here? Or that only checks `>0` so we should keep this semantically as mentioned above?

2023-03-08 21:56 UTC, andybradshaw commented on distgo/docker/docker_push.go
> +		if len(idxManifest.Manifests) != 1 {
Yeah, this is a slightly different semantic check. I'm not sure how we'd ever produce an image index with multiple manifests without including platform information... but if we run into a scenario where that happened, I'd rather bail out than publish any of the contained manifests.

2023-03-09 04:31 UTC, nmiyake approved these changes
Still have a few questions/feedback, but all of those items are purely stylistic, so providing approval to unblock.

2023-03-09 04:31 UTC, nmiyake commented on distgo/docker/docker_push.go
> +		if len(idxManifest.Manifests) != 1 {
OK yes, makes sense in that this is also checking if there are more than 1. To clarify, in the `types.OCIImageIndex`, could the size be different than 1 and it be OK?

Trying to understand why this check is performed here, since it doesn't seem like the logic between lines 154 - 160 would modify this value (would expect this check either at the beginning of the `case` block if it's just for this case, or before the entire `switch` block if expected for all cases)

2023-03-09 04:31 UTC, nmiyake commented on distgo/docker/docker_push.go
> +		platformInfo := indexManifest.Manifests[0].Platform != nil
Can you rename this variable `hasPlatformInfo` to make it clearer that it's a boolean value?

Based on the logic in this function, it seems like it's okay if there are multiple manifests as long as they are all of the same `MediaType`. In that scenario, why is it OK to check `Platform != nil` just for the 1st element? Is this value set/not being set guaranteed to be the same for all mainfests?

2023-03-09 04:31 UTC, nmiyake commented on distgo/docker/docker_push.go
> +		innerIndex, err := index.ImageIndex(idxManifest.Manifests[0].Digest)
`idxManifest.Manifests[0]` is referenced here and 3 other places (line 147, 165, 167). Is it not possible to extract this once at line 141 and comment as to what it is/why it's safe (that function before checks there is at least/only 1 element)? Would make it easier to be sure that the access is safe.

2023-03-09 16:40 UTC, andybradshaw commented on distgo/docker/docker_push.go
> +		innerIndex, err := index.ImageIndex(idxManifest.Manifests[0].Digest)
Pulled this into the manifestMetadata struct, so we only read from the index manifest's manifest list in one place.

2023-03-09 16:48 UTC, andybradshaw commented on distgo/docker/docker_push.go
> +		platformInfo := indexManifest.Manifests[0].Platform != nil
Renamed and updated to perform this check for all the manifests we iterate over. Was previously making the assumption that if the media type was the same, we'd write the same metadata fields for each of the manifests (platforms in this case). While that's true in practice for how docker is building things now, it's not guaranteed in the spec, so probably safer to confirm that we've got platform information for all manifests.

2023-03-09 17:02 UTC, andybradshaw commented on distgo/docker/docker_push.go
> +		if len(idxManifest.Manifests) != 1 {
Yes, when we have both image indexes and image manifests with platform information, we're fine with 1+ manifests. We could invert the platform info check and combine it with this if that makes it more explicit that we only care about there being exactly one when we don't have platform info.

2023-03-09 17:12 UTC, nmiyake approved these changes
Thanks, I think the code is much more readable after the refactors and this looks good!

2023-03-09 17:46 UTC, merged